// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Tooltip from "@visx/tooltip";

var Group = {};

var LinearGradient = {};

var D3 = {};

var Tree = {};

var $$Event = {};

var newrecord = Caml_obj.obj_dup(Tooltip.defaultStyles);

newrecord.borderRadius = "0.25rem";

newrecord.minWidth = "60";

newrecord.color = "white";

newrecord.backgroundColor = "rgba(0,0,0,0.7)";

var Tooltip$1 = {
  styles: newrecord
};

var LinkHorizontal = {};

var LinkRadial = {};

export {
  Group ,
  LinearGradient ,
  D3 ,
  Tree ,
  $$Event ,
  Tooltip$1 as Tooltip,
  LinkHorizontal ,
  LinkRadial ,
}
/* newrecord Not a pure module */
