// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Data from "../Data.bs.js";
import * as Tree from "./Tree.bs.js";
import * as WidgetModel from "../hooks/WidgetModel.bs.js";
import * as ModelContext from "./ModelContext.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function DataModel$WidgetPane(props) {
  WidgetModel.useState("tree");
  return JsxRuntime.jsx(Tree.make, {
              data: Data.rawTree,
              width: 600,
              height: 500
            });
}

var WidgetPane = {
  make: DataModel$WidgetPane
};

function DataModel$default(props) {
  return JsxRuntime.jsx(ModelContext.make, {
              model: props.model,
              children: JsxRuntime.jsx(DataModel$WidgetPane, {})
            });
}

var $$default = DataModel$default;

export {
  WidgetPane ,
  $$default ,
  $$default as default,
}
/* Tree Not a pure module */
