// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WidgetModel from "../hooks/WidgetModel.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function ModelContext(props) {
  return JsxRuntime.jsx(WidgetModel.Context.Provider.make, {
              value: props.model,
              children: props.children
            });
}

var make = ModelContext;

export {
  make ,
}
/* WidgetModel Not a pure module */
