// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Version from "./version";
import * as WidgetBs from "./Widget.bs";
import * as Base from "@jupyter-widgets/base";

var WidgetRegistry = {};

var App = {};

var Widget = {};

var Lumino = {
  App: App,
  Widget: Widget
};

var version = Version.MODULE_VERSION;

var name = Version.MODULE_NAME;

var JsPackage = {
  version: version,
  name: name
};

var widget = WidgetBs;

var extensionId = "" + name + ":plugin";

function activateWidgetExtension(_app, registry) {
  registry.registerWidget({
        name: name,
        version: version,
        exports: widget
      });
}

var examplePlugin_requires = [Base.IJupyterWidgetRegistry];

var examplePlugin = {
  id: extensionId,
  requires: examplePlugin_requires,
  activate: activateWidgetExtension,
  autoStart: true
};

var $$default = examplePlugin;

export {
  WidgetRegistry ,
  Lumino ,
  JsPackage ,
  widget ,
  extensionId ,
  activateWidgetExtension ,
  examplePlugin ,
  $$default ,
  $$default as default,
}
/* version Not a pure module */
